ekf_odom:
  ros__parameters:
    system:
      loop_rate: 20.0 # [Hz]
      use_sim_time: false
    
    model:
      wheel_radius: 0.033
      wheel_separation: 0.287
      imu_yaw_offset: 0.0
    
    tf:
      publish_tf: false
      frame_id: "odom"
      child_frame_id: "base_footprint"

    ekf:
      initial_covariance:
        diagonal: [0.5, 0.5, 0.05, 0.1, 0.1]
      process_noise:
        q_x: 0.05
        q_y: 0.05
        q_theta: 0.01
        q_v: 0.1
        q_w: 0.05
      measurement_noise:
        r_theta: 0.02
        r_w: 0.02

path_follower:
  ros__parameters:
    system:
      loop_rate: 20.0 # [Hz]
    
    model:
      max_lin_vel: 0.26
      max_ang_vel: 1.82
      lin_vel_step_size: 0.1
      ang_vel_step_size: 1.0

    control:
      path_relative_file: "path/rbp_path.csv"
      target_lin_vel: 0.2
      base_lookahead_distance: 0.3
      lookahead_gain: 0.2
      min_lookahead_distance: 0.2
      max_lookahead_distance: 1.0
      goal_tolerance: 0.05